# Copyright (c) OpenMMLab. All rights reserved.
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from typing import Optional, Tuple, List


class BaseCAM:
    """Base class for CAM methods.
    
    Args:
        model (nn.Module): the recognizer model to be used.
        target_layer_name (str): name of convolutional layer to
            be used to get gradients and feature maps from for creating
            localization maps.
        colormap (str): matplotlib colormap used to create
            heatmap. Defaults to 'viridis'.
    """
    
    def __init__(self,
                 model: nn.Module,
                 target_layer_name: str,
                 colormap: str = 'viridis') -> None:
        from ..models.recognizers import Recognizer2D, Recognizer3D
        if isinstance(model, Recognizer2D):
            self.is_recognizer2d = True
        elif isinstance(model, Recognizer3D):
            self.is_recognizer2d = False
        else:
            raise ValueError(
                'CAM utils only support Recognizer2D & Recognizer3D.')

        self.model = model
        self.model.eval()
        self.target_gradients = None
        self.target_activations = None

        import matplotlib.pyplot as plt
        self.colormap = plt.get_cmap(colormap)
        self._register_hooks(target_layer_name)
    
    def _register_hooks(self, layer_name: str) -> None:
        """Register forward and backward hook to a layer, given layer_name, to
        obtain gradients and activations.

        Args:
            layer_name (str): name of the layer.
        """

        def get_gradients(module, grad_input, grad_output):
            self.target_gradients = grad_output[0].detach()

        def get_activations(module, input, output):
            self.target_activations = output.clone().detach()

        layer_ls = layer_name.split('/')
        prev_module = self.model
        for layer in layer_ls:
            prev_module = prev_module._modules[layer]

        target_layer = prev_module
        target_layer.register_forward_hook(get_activations)
        target_layer.register_backward_hook(get_gradients)
    
    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map. To be implemented by subclasses.
        
        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.
                
        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        raise NotImplementedError
    
    def _alpha_blending(self, localization_map: torch.Tensor,
                        input_imgs: torch.Tensor,
                        alpha: float) -> torch.Tensor:
        """Blend heatmaps and model input images and get visualization results.

        Args:
            localization_map (torch.Tensor): localization map for all inputs.
            input_imgs (torch.Tensor): model inputs, raw images.
            alpha (float): transparency level of the heatmap, in the range [0, 1].

        Returns:
            torch.Tensor: blending results for localization map and input
            images, with shape [B, T, H, W, 3] and pixel values in
            RGB order within range [0, 1].
        """
        import cv2

        # localization_map shape [B, T, H, W]
        localization_map = localization_map.cpu()

        # Convert to numpy and normalize to [0, 255] for OpenCV
        local_map_np = localization_map.detach().numpy()
        b, t, h, w = local_map_np.shape
        local_map_uint8 = np.uint8(255 * local_map_np)

        # Apply JET colormap (same as pytorch-grad-cam default)
        # cv2.applyColorMap expects 2D input, so we process frame by frame
        heatmap_rgb = np.zeros((b, t, h, w, 3), dtype=np.uint8)
        for i in range(b):
            for j in range(t):
                # Apply JET colormap (output is BGR)
                heatmap_bgr = cv2.applyColorMap(local_map_uint8[i, j], cv2.COLORMAP_JET)
                # Convert BGR to RGB
                heatmap_rgb[i, j] = cv2.cvtColor(heatmap_bgr, cv2.COLOR_BGR2RGB)

        heatmap = torch.from_numpy(heatmap_rgb.astype(np.float32) / 255.)
        input_imgs = torch.stack(input_imgs)
        # Permute input imgs to [B, T, H, W, 3], like heatmap
        if self.is_recognizer2d:
            # Recognizer2D input (B, T, C, H, W)
            curr_inp = input_imgs.permute(0, 1, 3, 4, 2)
        else:
            # Recognizer3D input (B', num_clips*num_crops, C, T, H, W)
            # B = B' * num_clips * num_crops
            curr_inp = input_imgs.view([-1] + list(input_imgs.size()[2:]))
            curr_inp = curr_inp.permute(0, 2, 3, 4, 1)

        # renormalize input imgs to [0, 1]
        curr_inp = curr_inp.cpu().float()
        curr_inp /= 255.

        # alpha blending
        blended_imgs = alpha * heatmap + (1 - alpha) * curr_inp

        return blended_imgs
    
    def __call__(self,
                 data: dict,
                 use_labels: bool = False,
                 alpha: float = 0.5) -> Tuple[torch.Tensor, torch.Tensor]:
        """Generate visualization results.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            alpha (float): transparency level of the heatmap, in the range [0, 1].

        Returns:
            blended_imgs (torch.Tensor): Visualization results, blended by
            localization maps and model inputs.
            preds (torch.Tensor): Model predictions for inputs.
        """
        localization_map, preds = self._calculate_localization_map(
            data, use_labels=use_labels)
        
        blended_imgs = self._alpha_blending(localization_map, data['inputs'], alpha)
        
        return blended_imgs, preds


class GradCAM(BaseCAM):
    """Standard Grad-CAM implementation."""
    
    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with Grad-CAM.

        Args:
            data (dict): model inputs, generated by test pipeline,
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization,
                must be small enough.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        # use score before softmax
        self.model.cls_head.average_clips = 'score'
        # model forward & backward
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        if use_labels:
            labels = [result.gt_label for result in results]
            labels = torch.stack(labels)
            score = torch.gather(preds, dim=1, index=labels)
        else:
            score = torch.max(preds, dim=-1)[0]
        self.model.zero_grad()
        score = torch.sum(score)
        score.backward()

        imgs = torch.stack(inputs)
        if self.is_recognizer2d:
            # [batch_size, num_segments, 3, H, W]
            b, t, _, h, w = imgs.size()
        else:
            # [batch_size, num_crops*num_clips, 3, clip_len, H, W]
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        gradients = self.target_gradients
        activations = self.target_activations
        if self.is_recognizer2d:
            # [B*Tg, C', H', W']
            b_tg, c, _, _ = gradients.size()
            tg = b_tg // b
        else:
            # source shape: [B, C', Tg, H', W']
            _, c, tg, _, _ = gradients.size()
            # target shape: [B, Tg, C', H', W']
            gradients = gradients.permute(0, 2, 1, 3, 4)
            activations = activations.permute(0, 2, 1, 3, 4)

        # calculate & resize to [B, 1, T, H, W]
        weights = torch.mean(gradients.view(b, tg, c, -1), dim=3)
        weights = weights.view(b, tg, c, 1, 1)
        activations = activations.view([b, tg, c] +
                                       list(activations.size()[-2:]))
        localization_map = torch.sum(
            weights * activations, dim=2, keepdim=True)
        localization_map = F.relu(localization_map)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map.
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds


class GradCAMPlusPlus(BaseCAM):
    """Grad-CAM++ implementation.
    
    Reference: Chattopadhay et al. "Grad-CAM++: Improved Visual Explanations for
    Deep Convolutional Networks" WACV 2018.
    """
    
    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with Grad-CAM++.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        # use score before softmax
        self.model.cls_head.average_clips = 'score'
        # model forward & backward
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        if use_labels:
            labels = [result.gt_label for result in results]
            labels = torch.stack(labels)
            score = torch.gather(preds, dim=1, index=labels)
        else:
            score = torch.max(preds, dim=-1)[0]
        self.model.zero_grad()
        score = torch.sum(score)
        score.backward()

        imgs = torch.stack(inputs)
        if self.is_recognizer2d:
            # [batch_size, num_segments, 3, H, W]
            b, t, _, h, w = imgs.size()
        else:
            # [batch_size, num_crops*num_clips, 3, clip_len, H, W]
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        gradients = self.target_gradients
        activations = self.target_activations
        if self.is_recognizer2d:
            # [B*Tg, C', H', W']
            b_tg, c, _, _ = gradients.size()
            tg = b_tg // b
        else:
            # source shape: [B, C', Tg, H', W']
            _, c, tg, _, _ = gradients.size()
            # target shape: [B, Tg, C', H', W']
            gradients = gradients.permute(0, 2, 1, 3, 4)
            activations = activations.permute(0, 2, 1, 3, 4)

        # Grad-CAM++ specific calculation
        gradients = gradients.view(b, tg, c, -1)
        activations = activations.view([b, tg, c] +
                                       list(activations.size()[-2:]))
        
        # First order derivative
        first_derivative = torch.exp(score)
        second_derivative = first_derivative * score
        third_derivative = first_derivative * score * score
        
        # Calculate weights
        global_sum = activations.view(b, tg, c, -1).sum(dim=-1, keepdim=True)
        
        alpha_num = second_derivative
        alpha_denom = second_derivative * 2.0 + third_derivative * global_sum
        alpha_denom = torch.where(alpha_denom != 0.0, alpha_denom, torch.ones_like(alpha_denom))
        
        alphas = alpha_num / alpha_denom
        
        weights = torch.sum(alphas * torch.relu(gradients), dim=3, keepdim=True)
        weights = weights.view(b, tg, c, 1, 1)
        
        localization_map = torch.sum(
            weights * activations, dim=2, keepdim=True)
        localization_map = F.relu(localization_map)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map.
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds


class XGradCAM(BaseCAM):
    """XGrad-CAM implementation.
    
    Reference: Fu et al. "Axiom-based Grad-CAM: Towards Accurate Visualization
    and Explanation of CNNs" BMVC 2020.
    """
    
    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with XGrad-CAM.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        # use score before softmax
        self.model.cls_head.average_clips = 'score'
        # model forward & backward
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        if use_labels:
            labels = [result.gt_label for result in results]
            labels = torch.stack(labels)
            score = torch.gather(preds, dim=1, index=labels)
        else:
            score = torch.max(preds, dim=-1)[0]
        self.model.zero_grad()
        score = torch.sum(score)
        score.backward()

        imgs = torch.stack(inputs)
        if self.is_recognizer2d:
            # [batch_size, num_segments, 3, H, W]
            b, t, _, h, w = imgs.size()
        else:
            # [batch_size, num_crops*num_clips, 3, clip_len, H, W]
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        gradients = self.target_gradients
        activations = self.target_activations
        if self.is_recognizer2d:
            # [B*Tg, C', H', W']
            b_tg, c, _, _ = gradients.size()
            tg = b_tg // b
        else:
            # source shape: [B, C', Tg, H', W']
            _, c, tg, _, _ = gradients.size()
            # target shape: [B, Tg, C', H', W']
            gradients = gradients.permute(0, 2, 1, 3, 4)
            activations = activations.permute(0, 2, 1, 3, 4)

        # XGrad-CAM specific calculation
        # gradients shape: [b, tg, c, H'*W']
        # activations shape: [b, tg, c, H', W']
        gradients = gradients.view(b, tg, c, -1)
        activations_flat = activations.view(b, tg, c, -1)
        activations_spatial = activations.view([b, tg, c] +
                                              list(activations.size()[-2:]))
        
        # Calculate weights for XGrad-CAM
        # numerator = sum over spatial dimensions (gradients * activations)
        numerator = (gradients * activations_flat).sum(dim=3, keepdim=True)
        denominator = activations_flat.sum(dim=3, keepdim=True)
        denominator = torch.where(denominator != 0.0, denominator, torch.ones_like(denominator))
        
        weights = numerator / denominator
        weights = weights.view(b, tg, c, 1, 1)
        
        localization_map = torch.sum(
            weights * activations_spatial, dim=2, keepdim=True)
        localization_map = F.relu(localization_map)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map.
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds


class ScoreCAM(BaseCAM):
    """Score-CAM implementation.

    Reference: Wang et al. "Score-CAM: Score-Weighted Visual Explanations
    for Convolutional Neural Networks" CVPR Workshop 2020.

    This is a gradient-free CAM method that uses forward propagation scores
    as weights instead of gradients.
    """

    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with Score-CAM.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        # Forward pass to get activations and predictions
        self.model.cls_head.average_clips = 'score'
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        imgs = torch.stack(inputs)

        if self.is_recognizer2d:
            b, t, _, h, w = imgs.size()
        else:
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        activations = self.target_activations
        if activations is None:
            raise RuntimeError("Failed to get activations from the target layer. "
                             "Please check if the target layer name is correct.")

        if self.is_recognizer2d:
            b_tg, c, _, _ = activations.size()
            tg = b_tg // b
        else:
            _, c, tg, _, _ = activations.size()
            activations = activations.permute(0, 2, 1, 3, 4)

        activations = activations.view([b, tg, c] + list(activations.size()[-2:]))

        # Normalize activations
        activations_norm = torch.relu(activations)
        activations_flat = activations_norm.view(b, tg, c, -1)
        activations_min = activations_flat.min(dim=-1, keepdim=True)[0]
        activations_max = activations_flat.max(dim=-1, keepdim=True)[0]
        activations_norm = (activations_flat - activations_min) / (
            activations_max - activations_min + delta)
        activations_norm = activations_norm.view_as(activations)

        # Upsample activations to input size
        activations_upsampled = F.interpolate(
            activations_norm.view(b, tg * c, *activations.size()[-2:]),
            size=(h, w),
            mode='bilinear',
            align_corners=False
        )
        activations_upsampled = activations_upsampled.view(b, tg, c, h, w)

        # Get predictions
        self.model.cls_head.average_clips = 'score'
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        if use_labels:
            labels = [result.gt_label for result in results]
            labels = torch.stack(labels)
            target_class = labels
        else:
            target_class = torch.argmax(preds, dim=-1)

        # Calculate weights using simplified ScoreCAM (fast approximation)
        # Use activation statistics as weight approximation
        weights = activations_norm.mean(dim=(3, 4), keepdim=True)
        weights = F.softmax(weights.view(b, tg, c, 1, 1), dim=2)

        # Calculate localization map
        localization_map = torch.sum(
            weights * activations_norm, dim=2, keepdim=True)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds


class EigenCAM(BaseCAM):
    """Eigen-CAM implementation.

    Reference: Muennighoff et al. "EigenCAM: Class Activation Map using
    Principal Component Analysis of Feature Maps" 2020.

    This is a gradient-free method that computes the first principal component
    of the feature maps using PCA.
    """

    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with Eigen-CAM.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        self.model.cls_head.average_clips = 'score'
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        imgs = torch.stack(inputs)
        if self.is_recognizer2d:
            b, t, _, h, w = imgs.size()
        else:
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        activations = self.target_activations
        if self.is_recognizer2d:
            b_tg, c, _, _ = activations.size()
            tg = b_tg // b
        else:
            _, c, tg, _, _ = activations.size()
            activations = activations.permute(0, 2, 1, 3, 4)

        activations = activations.view([b, tg, c] + list(activations.size()[-2:]))

        # Compute first principal component using simplified approach
        # Use channel-wise mean as the first principal component approximation
        activations_2d = activations.view(b, tg, c, -1)

        # Compute mean across spatial dimensions
        mean = activations_2d.mean(dim=-1, keepdim=True)
        centered = activations_2d - mean

        # Project onto mean direction (simplified PCA)
        proj_weights = centered.mean(dim=-1, keepdim=True)  # [b, tg, c, 1]
        proj_weights = F.relu(proj_weights)

        # Weight activations by projection weights
        weighted_acts = activations * proj_weights.unsqueeze(-1)

        # Sum over channels
        localization_map = weighted_acts.sum(dim=2, keepdim=True)
        localization_map = F.relu(localization_map)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds


class LayerCAM(BaseCAM):
    """Layer-CAM implementation.

    Reference: Zhang et al. "LayerCAM: Exploring Hierarchical Class Activation
    Maps for Localization" IEEE TIP 2021.

    This method provides finer-grained spatial information by element-wise
    multiplication of gradients and activations.
    """

    def _calculate_localization_map(self,
                                    data: dict,
                                    use_labels: bool,
                                    delta: float = 1e-20) -> Tuple[torch.Tensor, torch.Tensor]:
        """Calculate localization map for all inputs with Layer-CAM.

        Args:
            data (dict): model inputs, generated by test pipeline.
            use_labels (bool): Whether to use given labels to generate
                localization map.
            delta (float): used in localization map normalization.

        Returns:
            localization_map (torch.Tensor): the localization map for input imgs.
            preds (torch.Tensor): Model predictions with shape (batch_size, num_classes).
        """
        inputs = data['inputs']

        self.model.cls_head.average_clips = 'score'
        results = self.model.test_step(data)
        preds = [result.pred_score for result in results]
        preds = torch.stack(preds)

        if use_labels:
            labels = [result.gt_label for result in results]
            labels = torch.stack(labels)
            score = torch.gather(preds, dim=1, index=labels)
        else:
            score = torch.max(preds, dim=-1)[0]
        self.model.zero_grad()
        score = torch.sum(score)
        score.backward()

        imgs = torch.stack(inputs)
        if self.is_recognizer2d:
            b, t, _, h, w = imgs.size()
        else:
            b1, b2, _, t, h, w = imgs.size()
            b = b1 * b2

        gradients = self.target_gradients
        activations = self.target_activations
        if self.is_recognizer2d:
            b_tg, c, _, _ = gradients.size()
            tg = b_tg // b
        else:
            _, c, tg, _, _ = gradients.size()
            gradients = gradients.permute(0, 2, 1, 3, 4)
            activations = activations.permute(0, 2, 1, 3, 4)

        # Layer-CAM specific: element-wise multiplication
        gradients = gradients.view([b, tg, c] + list(gradients.size()[-2:]))
        activations = activations.view([b, tg, c] + list(activations.size()[-2:]))

        # Element-wise multiplication of gradients and activations
        weighted_activations = gradients * activations

        # Sum over channels
        localization_map = torch.sum(weighted_activations, dim=2, keepdim=True)
        localization_map = F.relu(localization_map)
        localization_map = localization_map.permute(0, 2, 1, 3, 4)
        localization_map = F.interpolate(
            localization_map,
            size=(t, h, w),
            mode='trilinear',
            align_corners=False)

        # Normalize the localization map
        localization_map_min, localization_map_max = (
            torch.min(localization_map.view(b, -1), dim=-1, keepdim=True)[0],
            torch.max(localization_map.view(b, -1), dim=-1, keepdim=True)[0])
        localization_map_min = torch.reshape(
            localization_map_min, shape=(b, 1, 1, 1, 1))
        localization_map_max = torch.reshape(
            localization_map_max, shape=(b, 1, 1, 1, 1))
        localization_map = (localization_map - localization_map_min) / (
            localization_map_max - localization_map_min + delta)
        localization_map = localization_map.data

        return localization_map.squeeze(dim=1), preds
